#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
#define xd BitBlt
